services:
  app:
    container_name: app
    build: .
    ports: 
    - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    env_file:
    - .env
#    depends_on:
#     db:
#       condition: service_healthy
#   restart: always

# Setting up DB - no longer needed
#  db:
#    image: postgres:15-alpine
#    container_name: db
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
#        interval: 5s
#        timeout: 30s
#        retries: 5
#        start_period: 10s
#
#volumes:
#  postgres_data: